from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Protocol


class HermesFacade(Protocol):
    async def capabilities(self, profile: str) -> dict[str, Any]: ...
    async def list_conversations(
        self, profile: str, **params: Any
    ) -> dict[str, Any]: ...
    async def create_conversation(
        self, profile: str, body: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def get_conversation(
        self, profile: str, session_id: str
    ) -> dict[str, Any]: ...
    async def update_conversation(
        self, profile: str, session_id: str, body: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def set_conversation_model(
        self, profile: str, session_id: str, model: str
    ) -> dict[str, Any]: ...
    async def delete_conversation(self, profile: str, session_id: str) -> None: ...
    async def get_messages(
        self, profile: str, session_id: str, **params: Any
    ) -> dict[str, Any]: ...
    async def fork_conversation(
        self, profile: str, session_id: str, body: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def create_run(
        self, profile: str, body: dict[str, Any], idempotency_key: str
    ) -> dict[str, Any]: ...
    async def get_run(self, profile: str, run_id: str) -> dict[str, Any]: ...
    async def stream_run_events(
        self, profile: str, run_id: str
    ) -> AsyncIterator[dict[str, Any]]: ...
    async def cancel_run(self, profile: str, run_id: str) -> dict[str, Any]: ...
    async def steer_run(
        self, profile: str, run_id: str, instruction: str
    ) -> dict[str, Any]: ...
    async def answer_approval(
        self, profile: str, run_id: str, request_id: str, choice: str
    ) -> dict[str, Any]: ...
    async def list_scheduled_tasks(
        self, profile: str, *, include_disabled: bool = True
    ) -> dict[str, Any]: ...
    async def get_scheduled_task(self, profile: str, job_id: str) -> dict[str, Any]: ...
    async def update_scheduled_task(
        self, profile: str, job_id: str, body: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def delete_scheduled_task(self, profile: str, job_id: str) -> None: ...
    async def pause_scheduled_task(
        self, profile: str, job_id: str
    ) -> dict[str, Any]: ...
    async def resume_scheduled_task(
        self, profile: str, job_id: str
    ) -> dict[str, Any]: ...
    async def run_scheduled_task(self, profile: str, job_id: str) -> dict[str, Any]: ...
    async def models(self, profile: str) -> dict[str, Any]: ...
    async def toolsets(self, profile: str) -> dict[str, Any]: ...
